M48
; DRILL file {KiCad 8.0.3} date 2025-03-14T18:40:15+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-14T18:40:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X82.45Y-59.85
X82.45Y-79.2
X161.4Y-59.85
X161.45Y-79.2
M30
