M48
; DRILL file {KiCad 8.0.3} date 2025-03-14T18:24:48+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-14T18:24:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X71.58Y-80.425
X74.12Y-80.425
X76.66Y-80.425
X79.2Y-80.425
M30
